# Generated by Django 5.2.13 on 2026-06-03 06:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0008_clientcontact_is_portal_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientPortalOTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_otps",
                        to="clients.clientcontact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Portal OTP",
                "verbose_name_plural": "Client Portal OTPs",
                "ordering": ["-created_at"],
            },
        ),
    ]
