# Generated by Django 5.2.16 on 2026-08-19 06:51

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0034_historical_maintenancerecord"),
        ("dashboard", "0029_customfielddefinition_customfieldvalue_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("status", models.BooleanField(default=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("device_sn", models.CharField(max_length=255)),
                ("device_token", models.CharField(max_length=255)),
                (
                    "is_paired",
                    models.BooleanField(
                        choices=[(0, "unpaired"), (1, "pairing"), (2, "paired")],
                        default=0,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="asset",
                        to="assets.asset",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.organization",
                    ),
                ),
            ],
            options={
                "db_table": "device",
            },
        ),
        migrations.CreateModel(
            name="DeviceAttachments",
            fields=[
                ("status", models.BooleanField(default=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attahed_part", models.CharField(max_length=255)),
                ("mqtt_topic", models.CharField(max_length=500, unique=True)),
                ("is_enable", models.BooleanField(default=False)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_attachments",
                        to="iot.device",
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.organization",
                    ),
                ),
            ],
            options={
                "db_table": "device_attachments",
            },
        ),
        migrations.CreateModel(
            name="HistoricalDevice",
            fields=[
                ("status", models.BooleanField(default=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("device_sn", models.CharField(max_length=255)),
                ("device_token", models.CharField(max_length=255)),
                (
                    "is_paired",
                    models.BooleanField(
                        choices=[(0, "unpaired"), (1, "pairing"), (2, "paired")],
                        default=0,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="assets.asset",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dashboard.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical device",
                "verbose_name_plural": "historical devices",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDeviceAttachments",
            fields=[
                ("status", models.BooleanField(default=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("attahed_part", models.CharField(max_length=255)),
                ("mqtt_topic", models.CharField(db_index=True, max_length=500)),
                ("is_enable", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="iot.device",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dashboard.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical device attachments",
                "verbose_name_plural": "historical device attachmentss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSensor",
            fields=[
                ("status", models.BooleanField(default=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("temperature", "Temperature"),
                            ("humidity", "Humidity"),
                            ("vibration", "Vibration / Shock"),
                            ("power", "Power Consumption"),
                            ("voltage", "Voltage"),
                            ("current", "Current"),
                            ("gps_lat", "GPS Latitude"),
                            ("gps_lng", "GPS Longitude"),
                            ("pressure", "Pressure"),
                            ("flow_rate", "Flow Rate"),
                            ("runtime_hrs", "Runtime Hours"),
                        ],
                        max_length=80,
                    ),
                ),
                ("unit", models.CharField(max_length=50)),
                ("mqtt_topic", models.CharField(db_index=True, max_length=500)),
                (
                    "is_paired",
                    models.BooleanField(
                        choices=[(0, "unpaired"), (1, "pairing"), (2, "paired")],
                        default=0,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="iot.device",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dashboard.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sensor",
                "verbose_name_plural": "historical sensors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("status", models.BooleanField(default=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("temperature", "Temperature"),
                            ("humidity", "Humidity"),
                            ("vibration", "Vibration / Shock"),
                            ("power", "Power Consumption"),
                            ("voltage", "Voltage"),
                            ("current", "Current"),
                            ("gps_lat", "GPS Latitude"),
                            ("gps_lng", "GPS Longitude"),
                            ("pressure", "Pressure"),
                            ("flow_rate", "Flow Rate"),
                            ("runtime_hrs", "Runtime Hours"),
                        ],
                        max_length=80,
                    ),
                ),
                ("unit", models.CharField(max_length=50)),
                ("mqtt_topic", models.CharField(max_length=500, unique=True)),
                (
                    "is_paired",
                    models.BooleanField(
                        choices=[(0, "unpaired"), (1, "pairing"), (2, "paired")],
                        default=0,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device",
                        to="iot.device",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.organization",
                    ),
                ),
            ],
            options={
                "db_table": "sensor",
            },
        ),
        migrations.CreateModel(
            name="SensorThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("gt", "Greater Than"),
                            ("lt", "Less Than"),
                            ("eq", "Equal To"),
                            ("neq", "Not Equal To"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thresholds",
                        to="iot.sensor",
                    ),
                ),
            ],
            options={
                "db_table": "sensor_threshold",
            },
        ),
    ]
