# Generated by Django 5.2.13 on 2026-08-24 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_customfielddefinition_customfieldvalue_and_more"),
        ("iot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceattachments",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.organization",
            ),
        ),
    ]
