# Generated by Django 5.2.14 on 2026-08-27 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0003_sensorthreshold_alert_type_sensoralarm"),
        ("support", "0012_populate_happy_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensoralarm",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alarms",
                to="support.supportticket",
            ),
        ),
    ]
