# Generated by Django 5.2.14 on 2026-09-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumable",
            name="consumable_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalconsumable",
            name="consumable_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
