# Generated by Django 5.2.16 on 2026-09-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0004_consumabledocument'),
        ('dashboard', '0029_customfielddefinition_customfieldvalue_and_more'),
        ('products', '0019_rename_product_category_historicalproduct_product_sub_category_and_more'),
        ('vendors', '0009_alter_historicalvendor_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='consumable_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalconsumable',
            name='consumable_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='consumable',
            constraint=models.UniqueConstraint(fields=('organization', 'consumable_id'), name='unique_consumable_id_per_organization'),
        ),
    ]
