# Generated by Django 5.2.16 on 2026-09-29 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0005_consumable_consumable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='is_serialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalconsumable',
            name='is_serialized',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ConsumableUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('serial_no', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('checked_out', 'Checked Out'), ('lost', 'Lost'), ('disposed', 'Disposed')], default='in_stock', max_length=20)),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='consumables.consumablecheckout')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='consumables.consumable')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('consumable', 'sequence'), name='unique_unit_sequence_per_consumable'), models.UniqueConstraint(condition=models.Q(('serial_no__isnull', False)), fields=('consumable', 'serial_no'), name='unique_unit_serial_per_consumable')],
            },
        ),
    ]
