# Generated by Django 5.2.11 on 2026-04-22 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0031_assignasset_issue_date_assignasset_notes'),
        ('vendors', '0009_alter_historicalvendor_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.IntegerField(choices=[(0, 'Outward'), (1, 'Inward')], default=0)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('purpose_of_movement', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Draft'), (3, 'Rejected')], default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assets.asset')),
                ('authorised_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gatepasses_authorised', to=settings.AUTH_USER_MODEL)),
                ('destination_vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendors.vendor')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gatepasses_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
