# Generated by Django 5.2.13 on 2026-06-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gate_pass", "0002_alter_gatepass_authorised_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gatepass",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Approved"),
                    (2, "Draft"),
                    (3, "Rejected"),
                    (4, "Checked Out"),
                ],
                default=0,
            ),
        ),
    ]
