# Generated by Django 5.2.11 on 2026-05-24 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0031_assignasset_issue_date_assignasset_notes'),
        ('dashboard', '0027_historicallicensetype'),
        ('gate_pass', '0002_alter_gatepass_authorised_by_and_more'),
        ('vendors', '0009_alter_historicalvendor_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.organization'),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gatepasses_authorised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='destination_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gatepasses_raised', to=settings.AUTH_USER_MODEL),
        ),
    ]
