# Generated by Django 5.1.5 on 2025-08-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Assigned'), (1, 'Available'), (2, 'Under Maitainance'), (3, 'Decommissioned')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Assigned'), (1, 'Available'), (2, 'Under Maitainance'), (3, 'Decommissioned')], default=0),
        ),
    ]
