# Generated by Django 5.1.5 on 2025-08-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_status_alter_historicalasset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Assigned'), (1, 'Available'), (2, 'Repair Required'), (3, 'Lost/Stolen'), (4, 'Broken'), (5, 'Ready To Deploy'), (6, 'Out for Repair')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Assigned'), (1, 'Available'), (2, 'Repair Required'), (3, 'Lost/Stolen'), (4, 'Broken'), (5, 'Ready To Deploy'), (6, 'Out for Repair')], default=0),
        ),
    ]
