# Generated by Django 3.2 on 2022-07-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20220621_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
