# Generated by Django 3.2 on 2022-09-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20220929_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='deleted',
        ),
    ]
