# Generated by Django 3.2 on 2022-10-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20221013_0710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
