# Generated by Django 3.2 on 2022-10-13 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_delete_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetspecification',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
    ]
