# Generated by Django 3.2 on 2022-10-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_alter_assetspecification_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
