# Generated by Django 3.2 on 2022-11-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_assignasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignasset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assignasset',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='assignasset',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='assignasset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='assignasset',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='assignasset',
            name='updated_by',
        ),
    ]
