# Generated by Django 5.1.5 on 2025-08-06 09:36

import assets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_historicalasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Assigned'), (1, 'Available'), (2, 'Under Maitainance'), (3, 'Decommissioned')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Assigned'), (1, 'Available'), (2, 'Under Maitainance'), (3, 'Decommissioned')], default=0),
        ),
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=assets.models.path_and_rename)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assets.asset')),
            ],
        ),
    ]
