# Generated by Django 5.1.5 on 2025-08-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_asset_tag_historicalasset_tag_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Assigned'), (1, 'Available'), (2, 'Repair Required'), (3, 'Lost/Stolen'), (4, 'Broken'), (5, 'Ready To Deploy'), (6, 'Out for Repair')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Assigned'), (1, 'Available'), (2, 'Repair Required'), (3, 'Lost/Stolen'), (4, 'Broken'), (5, 'Ready To Deploy'), (6, 'Out for Repair')], default=1),
        ),
    ]
