# Generated by Django 5.1.5 on 2025-08-14 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_asset_asset_status_historicalasset_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assets.assetstatus'),
        ),
    ]
