# Generated by Django 5.1.5 on 2025-09-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_assignasset_assigned_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignasset',
            name='assigned_date',
        ),
    ]
