# Generated by Django 5.1.5 on 2025-10-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_alter_asset_tag_alter_historicalasset_tag'),
        ('assets', '0027_slackwebhook'),
    ]

    operations = [
    ]
