# Generated by Django 5.1.5 on 2025-11-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_slackwebhook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlackWebhook',
        ),
    ]
