# Generated by Django 5.2.11 on 2026-04-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0030_alter_asset_options_alter_assetimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignasset',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignasset',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
