# Generated by Django 5.2.13 on 2026-05-12 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0031_assignasset_issue_date_assignasset_notes"),
        ("clients", "0006_add_client_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="assets",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="historicalasset",
            name="client",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clients.client",
            ),
        ),
    ]
