# Generated by Django 5.2.13 on 2026-05-12 05:47

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0027_historicallicensetype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_id", models.CharField(blank=True, max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "rental_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Tech Equipment", "Tech Equipment"),
                            ("Heavy Machinery", "Heavy Machinery"),
                            ("Office Infrastructure", "Office Infrastructure"),
                            ("Energy Systems", "Energy Systems"),
                            ("Transport Vehicles", "Transport Vehicles"),
                            ("Medical Equipment", "Medical Equipment"),
                            ("Other", "Other"),
                        ],
                        default="Tech Equipment",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("active_rentals", models.PositiveIntegerField(default=0)),
                ("open_tickets", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Review", "Review"),
                            ("Dormant", "Dormant"),
                            ("Inactive", "Inactive"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalClient",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "client_id",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rental_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Tech Equipment", "Tech Equipment"),
                            ("Heavy Machinery", "Heavy Machinery"),
                            ("Office Infrastructure", "Office Infrastructure"),
                            ("Energy Systems", "Energy Systems"),
                            ("Transport Vehicles", "Transport Vehicles"),
                            ("Medical Equipment", "Medical Equipment"),
                            ("Other", "Other"),
                        ],
                        default="Tech Equipment",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("active_rentals", models.PositiveIntegerField(default=0)),
                ("open_tickets", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Review", "Review"),
                            ("Dormant", "Dormant"),
                            ("Inactive", "Inactive"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dashboard.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical client",
                "verbose_name_plural": "historical clients",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
