# Generated by Django 5.2.13 on 2026-05-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clients",
            "0002_client_city_client_corporate_website_client_industry_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[(1, "Active"), (2, "Review"), (3, "Dormant"), (0, "Inactive")],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="status",
            field=models.CharField(
                choices=[(1, "Active"), (2, "Review"), (3, "Dormant"), (0, "Inactive")],
                default="Active",
                max_length=20,
            ),
        ),
    ]
