# Generated by Django 5.2.13 on 2026-05-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_update_status_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "Active"),
                    ("2", "Review"),
                    ("3", "Dormant"),
                    ("0", "Inactive"),
                ],
                default="1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "Active"),
                    ("2", "Review"),
                    ("3", "Dormant"),
                    ("0", "Inactive"),
                ],
                default="1",
                max_length=20,
            ),
        ),
    ]
