# Generated by Django 5.2.13 on 2026-05-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_update_status_default_string"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ["-created_at"]},
        ),
    ]
