# Generated by Django 5.2.13 on 2026-05-14 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_add_client_field"),
        ("roles", "0004_alter_role_created_at_alter_role_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="client",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="client",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="client",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="client",
            name="role",
        ),
        migrations.RemoveField(
            model_name="historicalclient",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="historicalclient",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="historicalclient",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="historicalclient",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="historicalclient",
            name="role",
        ),
        migrations.CreateModel(
            name="ClientContact",
            fields=[
                ("status", models.BooleanField(default=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=45, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="clients.client",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_roles",
                        to="roles.role",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
