# Generated by Django 5.2.13 on 2026-06-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_remove_client_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcontact",
            name="is_portal_active",
            field=models.BooleanField(default=False),
        ),
    ]
