# Generated by Django 5.2.14 on 2026-07-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_clientcontact_is_portal_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="happy_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="happy_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
