# Generated by Django 5.2.14 on 2026-07-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0009_client_happy_code_historicalclient_happy_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="happy_code",
        ),
        migrations.RemoveField(
            model_name="historicalclient",
            name="happy_code",
        ),
    ]
