# Generated by Django 3.2 on 2022-07-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220703_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
