# Generated by Django 3.2 on 2022-09-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_producttype_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='deleted',
        ),
    ]
