# Generated by Django 3.2 on 2022-09-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_producttype_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
