# Generated by Django 3.2 on 2022-09-30 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_location_is_deleted'),
        ('dashboard', '0011_productcategory_is_deleted'),
    ]

    operations = [
    ]
