# Generated by Django 3.2 on 2022-10-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_merge_20220930_0513'),
        ('dashboard', '0013_department_is_deleted'),
    ]

    operations = [
    ]
