# Generated by Django 3.2 on 2022-10-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_merge_20221006_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
