# Generated by Django 3.2 on 2022-12-12 13:17

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.path_and_rename),
        ),
    ]
