# Generated by Django 5.1.5 on 2025-08-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_historicalproductcategory_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducttype',
            name='can_modify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='can_modify',
            field=models.BooleanField(default=True),
        ),
    ]
