# Generated by Django 5.1.5 on 2025-08-14 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_historicalproducttype_can_modify_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('entity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=30)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_value', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_type', models.CharField(choices=[('asset', 'Asset'), ('product', 'Product'), ('vendor', 'Vendor')], max_length=30)),
                ('required', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization')),
            ],
        ),
    ]
