# Generated by Django 5.1.5 on 2025-08-14 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_customfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization'),
        ),
    ]
