# Generated by Django 5.1.5 on 2025-08-14 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_customfield_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
