# Generated by Django 5.2.14 on 2026-07-07 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0010_remove_client_happy_code_and_more"),
        ("dashboard", "0027_historicallicensetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallocation",
            name="client",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="clients.client",
            ),
        ),
    ]
