# Generated by Django 5.2.14 on 2026-08-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_historicallocation_client_location_client"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomField",
        ),
    ]
