# Generated by Django 5.2.13 on 2026-06-03 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_clientcontact_is_portal_active"),
        ("support", "0003_delete_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsupportticket",
            name="client",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupportticket",
            name="created_by_contact",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="clients.clientcontact",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_tickets",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="created_by_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tickets",
                to="clients.clientcontact",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportticket",
            name="impact_level",
            field=models.CharField(
                choices=[
                    ("3", "Critical"),
                    ("2", "High"),
                    ("1", "Medium"),
                    ("0", "Low"),
                ],
                default="1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("3", "Emergency"),
                    ("2", "High"),
                    ("1", "Medium"),
                    ("0", "Low"),
                ],
                default="1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsupportticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "Open"),
                    ("1", "In Progress"),
                    ("2", "In Testing"),
                    ("3", "Resolved"),
                    ("4", "Closed"),
                ],
                default="0",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="impact_level",
            field=models.CharField(
                choices=[
                    ("3", "Critical"),
                    ("2", "High"),
                    ("1", "Medium"),
                    ("0", "Low"),
                ],
                default="1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("3", "Emergency"),
                    ("2", "High"),
                    ("1", "Medium"),
                    ("0", "Low"),
                ],
                default="1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "Open"),
                    ("1", "In Progress"),
                    ("2", "In Testing"),
                    ("3", "Resolved"),
                    ("4", "Closed"),
                ],
                default="0",
                max_length=20,
            ),
        ),
    ]
