# Generated by Django 5.2.13 on 2026-06-30 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_clientcontact_is_portal_active"),
        ("support", "0006_remove_ticketattachment_activity_ticketcomment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcomment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_comments",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_comments",
                to="clients.clientcontact",
            ),
        ),
    ]
