# Generated by Django 5.2.13 on 2026-07-01 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_clientcontact_is_portal_active"),
        ("support", "0007_ticketcomment_client_ticketcomment_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketactivity",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.clientcontact",
            ),
        ),
    ]
