# Generated by Django 5.2.14 on 2026-07-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_ticketactivity_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='is_staff_comment',
            field=models.BooleanField(default=False),
        ),
    ]
