"""
Django settings for AssetManagement project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import json
import os
from datetime import timedelta
from pathlib import Path

import firebase_admin
from cryptography.fernet import Fernet
from decouple import config
from dotenv import load_dotenv
from firebase_admin import credentials

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env", override=True)
cipher_suite = Fernet(b"NlISlEq9jlxcgOhAQpe4dN0hAeuwxmRCiTZzhrX7nic=")

file_name = os.getenv(
    "FIREBASE_APPLICATION_CREDENTIALS_FILE_DIRECTORY", "firebase-credentials.json"
)
firebase_credentials = os.getenv("FIREBASE_CREDENTIALS")

if firebase_credentials:
    fernet = Fernet(os.getenv("FERNET_KEY").encode())
    decrypted = fernet.decrypt(firebase_credentials.encode())
    cred_dict = json.loads(decrypted.decode())

    cred = credentials.Certificate(cred_dict)
    firebase_admin.initialize_app(cred)

elif file_name and file_name.strip().strip("'\""):
    cred_path = BASE_DIR / file_name.strip().strip("'\"")
    if cred_path.is_file():
        cred = credentials.Certificate(cred_path)
        firebase_admin.initialize_app(cred)

LOGIN_REDIRECT_URL = "/"

DEBUG = True

CELERY_BROKER_URL = "redis://127.0.0.1:6380/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6380/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_TASK_TIME_LIMIT = 30  # hard kill
CELERY_TASK_SOFT_TIME_LIMIT = 25  # graceful timeout

# Daily re-validation of paid-extension licenses against the external
# license server (a separate project — see docs/extension-architecture.md
# §5). Requires `celery beat` to be running; harmless if it isn't (the
# task simply never fires, existing cached valid_until keeps governing
# require_license()).
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    "revalidate-extension-licenses-daily": {
        "task": "configurations.extensions.tasks.revalidate_extension_licenses",
        "schedule": crontab(hour=3, minute=0),
    },
}

# Base URL of the external license server (separate project, not built in
# this repo). Unset by default — activate_extension/revalidate_extension_licenses
# are no-ops until this is configured.
LICENSE_SERVER_URL = os.environ.get("LICENSE_SERVER_URL")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG") or False
if DEBUG:
    ALLOWED_HOSTS = ["*"]

else:
    ALLOWED_HOSTS = (
        [os.environ.get("ALLOWED_HOSTS")]
        if os.environ.get("ALLOWED_HOSTS")
        else [".onrender.com"]
    )

CSRF_TRUSTED_ORIGINS = (
    [os.environ.get("CSRF_TRUSTED_ORIGINS")]
    if os.environ.get("CSRF_TRUSTED_ORIGINS")
    else ["https://*.onrender.com"]
)

LOCALHOST_URL = "http:127.0.0.1:8000"
DEV_URL = os.environ.get("DEV_URL") if os.getcwd() == "/app" else None

# Application definition

STATIC_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "django_htmx",
    "authentication",
    "vendors",
    "products",
    "assets",
    "dashboard",
    "recycle_bin",
    "upload",
    "error_handlers",
    "smart_selects",
    "roles",
    "users",
    "notifications",
    "simple_history",
    "configurations",
    "drf_spectacular",
    "audit",
    "license",
    # 'silk'
    "gate_pass",
    "clients",
    "client_portal",
    "custom_fields",
]

# Extension apps enabled via `python manage.py enable_extension` are appended
# here from extensions/registry.json — never edited by hand. See
# docs/extension-architecture.md §2. Read here (not from the DB) because
# settings.py runs before the ORM/app registry exists; a missing or corrupt
# registry degrades to an empty list rather than crashing startup.
from configurations.extensions.apps_loader import (  # noqa: E402
    get_extension_override_dirs,
    load_enabled_extension_apps,
)

INSTALLED_APPS = STATIC_APPS + load_enabled_extension_apps(BASE_DIR)

# Override folders (extensions/<name>/, no core/ prefix) are templates and
# static assets only — never a second INSTALLED_APPS entry, so they can't
# collide with the core extension's app label/models. Listed first in
# TEMPLATES DIRS / STATICFILES_DIRS below so they win over the core app's
# own resources. See docs/extension-architecture.md §9.
EXTENSION_OVERRIDE_DIRS = get_extension_override_dirs(BASE_DIR)

# Gunicorn's --pid file; the Extensions admin page sends SIGHUP to this PID
# to gracefully activate pending extension changes. Absent under
# `manage.py runserver` (local dev), which is fine — the reload button is a
# no-op there. See docs/extension-architecture.md §4.
GUNICORN_PID_FILE = os.environ.get("GUNICORN_PID_FILE", str(BASE_DIR / "gunicorn.pid"))
# FIREBASE_APP = initialize_app()
ENABLE_TRACEBACK = True
TRACEBACK_SHOW_LOCALS = True
TRACEBACK_LOCALS_MAX_LENGTH = None  # Set to None to show full locals information
PRINT_TRACEBACK_INFO_TO_CONSOLE = True  # Set to False if not required
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "client_portal.middleware.ClientPortalMiddleware",
]

ROOT_URLCONF = "AssetManagement.urls"

WSGI_APPLICATION = "AssetManagement.wsgi.application"

BASE_DIR = Path(__file__).resolve().parent.parent

try:
    os.environ["DB_ENGINE"]
    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [*[d / "templates" for d in EXTENSION_OVERRIDE_DIRS], BASE_DIR / "templates"],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                    "configurations.context_processors.sidebar_logo",
                    "configurations.context_processors.favicon_image",
                    "configurations.context_processors.login_page_logo",
                    "django.template.context_processors.request",
                    "configurations.context_processors.translations",
                    "configurations.context_processors.extension_menu",
                ],
            },
        },
    ]
except Exception:
    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [*[d / "templates" for d in EXTENSION_OVERRIDE_DIRS], BASE_DIR / "templates"],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                    "configurations.context_processors.translations",
                    "configurations.context_processors.extension_menu",
                ],
            },
        },
    ]

WSGI_APPLICATION = "AssetManagement.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE"),
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USERNAME"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
    }
}
# DATABASES = {
#        'default': {
#            'ENGINE': 'django.db.backends.sqlite3',
#            'NAME': BASE_DIR / 'db.sqlite3',
#        }
#    }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [*[d / "static" for d in EXTENSION_OVERRIDE_DIRS], BASE_DIR / "static"]

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "authentication.User"
LOGIN_URL = "authentication:login"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = os.environ.get("EMAIL_PORT")
EMAIL_USE_TLS = False
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")

# Image Processing
DJANGORESIZED_DEFAULT_SIZE = [1024, 768]
DJANGORESIZED_DEFAULT_QUALITY = 75
DJANGORESIZED_DEFAULT_KEEP_META = True
DJANGORESIZED_DEFAULT_FORCE_FORMAT = "JPEG"
DJANGORESIZED_DEFAULT_FORMAT_EXTENSIONS = {"JPEG": ".jpg"}
DJANGORESIZED_DEFAULT_NORMALIZE_ROTATION = True
DATA_UPLOAD_MAX_NUMBER_FIELDS = 3000  # or higher if needed

APPEND_SLASH = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication"
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": (
        timedelta(minutes=2) if not DEBUG else timedelta(minutes=720)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "TOKEN_REFRESH_SERIALIZER": "authentication.serializers.RefreshTokenSerializer",
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "ON_LOGIN_SUCCESS": "rest_framework_simplejwt.serializers.default_on_login_success",
    "ON_LOGIN_FAILED": "rest_framework_simplejwt.serializers.default_on_login_failed",
}

SPECTACULAR_SETTINGS = {
    "COMPONENT_SPLIT_REQUEST": True,  # Splits FileField schemas for request/response
    # Other settings like TITLE, VERSION, etc.
    "SWAGGER_OPTIONS": {"persistAuthorization": True},
}
