from django.urls import path
from .views.branding_views import *
from .views.extentions_views import *
from .views.localization_views import *
from .views.organizations_views import add_organization
from .views.tag_configurations_views import *

from . import api_views

app_name = 'configurations'

urlpatterns=[
    path('upload-logo/',logo_upload,name='upload_logo'),
    path('delete-logo/<int:id>',delete_logo,name='delete_logo'),
    path('delete-favicon/<int:id>',delete_favicon,name='delete_favicon'),
    path('delete-login-page-logo/<int:id>',delete_login_page_logo,name='delete_login_page_logo'),


    path('update-tag-configuration/<str:id>/', create_or_update_tag_configuration, name='update_tag_configuration'),
    path('update-tag-configuration/', create_or_update_tag_configuration, name='update_tag_configuration_without_id'),
    path('list-tag-configuration/', list_tag_configurations, name='list_tag'),
    path('toggle-default-settings/<str:id>/', toggle_default_settings, name='toggle_default_settings'),
    
    path('list-localization/', list_localizations, name='list_localization'),
    path('create-localization-configuration/', create_localization_configuration, name='create_localization_configuration'),
    
    path('integration/',integration, name='integration'),
    path('list_extensions/', list_extensions, name='list_extensions'),
    path('extension-status/<uuid:id>/', extension_status, name='extension_status'),
    path('add-configurations/',save_slack_configuration,name='save_slack_configuration'),
    
    path('add-organization/',add_organization,name='add_organization'),

    #for api extension
    path('api-extension-status/<uuid:id>',api_extension_status,name='api_extension_status'),

    # extension system — read-only status + apply-pending-restart, per
    # docs/extension-architecture.md §4. Install/enable/disable stay CLI-only.
    path('extensions/manage/', manage_extensions, name='manage_extensions'),
    path('extensions/apply-changes/', trigger_extension_reload, name='trigger_extension_reload'),
]

configuration_api_url_patterns = [
    #api urls
    path('api/configuration/tag/',api_views.GetTagConfiguration.as_view(),name="complete_audit_list"),
    path('api/configuration/localization/',api_views.GetLocalizationConfiguration.as_view(),name='pending_audit_list'),
    path('api/configuration/auto-generated-tag/',api_views.AutoGeneratedTag.as_view(),name='auto_generated_tag')
]