from django.urls import path
from django.views.generic import TemplateView
# from .views import OrganizationLogo
from . import views
from . import api_views

app_name = 'configurations'

urlpatterns=[
    path('upload-logo/',views.logo_upload,name='upload_logo'),
    path('delete-logo/<int:id>',views.delete_logo,name='delete_logo'),
    path('delete-favicon/<int:id>',views.delete_favicon,name='delete_favicon'),
    path('delete-login-page-logo/<int:id>',views.delete_login_page_logo,name='delete_login_page_logo'),
    path('update-tag-configuration/<str:id>/', views.create_or_update_tag_configuration, name='update_tag_configuration'),
    path('update-tag-configuration/', views.create_or_update_tag_configuration, name='update_tag_configuration_without_id'),
    path('list-tag-configuration/', views.list_tag_configurations, name='list_tag'),
    path('toggle-default-settings/<str:id>/', views.toggle_default_settings, name='toggle_default_settings'),
    path('list-localization/', views.list_localizations, name='list_localization'),
    path('create-localization-configuration/', views.create_localization_configuration, name='create_localization_configuration'),
    path('integration/', views.integration, name='integration'),
    path('list_extensions/', views.list_extensions, name='list_extensions'),
    path('extension-status/<uuid:id>/', views.extension_status, name='extension_status'),
    path('add-configurations/',views.save_slack_configuration,name='save_slack_configuration'),
    path('add-organization/',views.add_organization,name='add_organization'),

    #for api extension
    path('api-extension-status/<uuid:id>',views.api_extension_status,name='api_extension-status')
]

configuration_api_url_patterns = [
    #api urls
    path('api/configuration/tag/',api_views.GetTagConfiguration.as_view(),name="complete_audit_list"),
    path('api/configuration/localization/',api_views.GetLocalizationConfiguration.as_view(),name='pending_audit_list'),
    path('api/configuration/auto-generated-tag/',api_views.AutoGeneratedTag.as_view(),name='auto_generated_tag')
]