# Generated by Django 5.2.16 on 2026-09-05 19:00

import django.db.models.deletion
import google_integration.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCloudFirebaseConfig",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("is_connected", models.BooleanField(default=False)),
                (
                    "gcp_project_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gcp_project_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "firebase_web_app_id",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "web_api_key",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "web_auth_domain",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "web_project_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "web_storage_bucket",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "web_messaging_sender_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("web_app_id", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "web_vapid_key",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "encrypted_service_account_json",
                    google_integration.fields.EncryptedTextField(blank=True, null=True),
                ),
                (
                    "encrypted_oauth_refresh_token",
                    google_integration.fields.EncryptedTextField(blank=True, null=True),
                ),
                ("oauth_token_scopes", models.TextField(blank=True, null=True)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
