# Generated by Django 3.2 on 2022-09-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_rename_profile_pic_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
