# Generated by Django 3.2 on 2022-10-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20221018_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.BooleanField(choices=[(False, 'Only Assigned'), (True, 'All')]),
        ),
    ]
