# Generated by Django 3.2 on 2022-11-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.BooleanField(choices=[(False, 'Only Assigned'), (True, 'All')], default=False),
        ),
    ]
