# Generated by Django 5.1.5 on 2025-08-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_historicaluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeded', models.BooleanField(default=False)),
            ],
        ),
    ]
