# Generated by Django 5.2.8 on 2026-01-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_historicaluser_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
