# Generated by Django 5.2.11 on 2026-02-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_historicaluser_two_factor_auth_user_two_factor_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertotp',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
