# Generated by Django 5.2.11 on 2026-02-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_usertotp_is_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertotp',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
