# Generated by Django 5.2.11 on 2026-04-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_usertotp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='use_expired_assets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='use_expired_assets',
            field=models.BooleanField(default=False),
        ),
    ]
