# Generated by Django 5.2.13 on 2026-06-15 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0031_historicaluser_use_expired_assets_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usertotp",
            old_name="is_logged_in",
            new_name="is_validate",
        ),
        migrations.RemoveField(
            model_name="usertotp",
            name="status",
        ),
        migrations.RemoveField(
            model_name="usertotp",
            name="user_id",
        ),
        migrations.AddField(
            model_name="usertotp",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_totp",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
