# Generated by Django 5.2.14 on 2026-06-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_rename_is_logged_in_usertotp_is_validate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertotp',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
