# Generated by Django 5.2.14 on 2026-07-07 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0033_usertotp_is_logged_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in standard format with + followed by country code and number (10-15 digits total, e.g., +919876543210).",
                        regex="^\\+[1-9]\\d{9,14}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in standard format with + followed by country code and number (10-15 digits total, e.g., +919876543210).",
                        regex="^\\+[1-9]\\d{9,14}$",
                    )
                ],
            ),
        ),
    ]
