from django.shortcuts import render, redirect
from django.core.cache import cache
from django.conf import settings
import os
from django.contrib import messages
from django.contrib.auth.decorators import (login_required,permission_required,user_passes_test,)
from django.core.cache import cache
from django.core.paginator import Paginator
from django.db.models import Count,Q
from django.http import (HttpResponse,HttpResponseBadRequest,JsonResponse,)
from django.shortcuts import get_object_or_404, redirect, render
from audit.models import Audit, AuditImage
from authentication.models import User
from dashboard.models import CustomField
from .barcode import generate_barcode
from .forms import (AssetForm,AssignedAssetListForm,AssetImageForm,ReassignedAssetForm)
from .models import Asset, AssetImage, AssetSpecification, AssetStatus, AssignAsset
from .utils import (asset_details, autogenerated_tag, create_char_data, create_custom_fileds,delete_asset_images, filtered_asset,create_asset_list, save_new_images, search_with_filters, update_existing_custom_fields)
from configurations.models import SlackConfiguration 
import base64
from .utils import slack_notification
from assets.forms import AssignedAssetForm,ReassignedAssetForm
from configurations.forms import ClientCredentialsForm
import json
import requests
from configurations.utils import generate_asset_tag
from notifications.models import Notification
from notifications.utils import notifications_call,send_email