import json
import os
from django.contrib import messages
from django.contrib.auth.decorators import (login_required,permission_required,user_passes_test,)
from django.core.cache import cache
from django.core.paginator import Paginator
from django.db.models import Count,Q
from django.http import (HttpResponse,HttpResponseBadRequest,JsonResponse,)
from django.shortcuts import get_object_or_404, redirect, render
from audit.models import Audit, AuditImage
from authentication.models import User
from dashboard.models import CustomField
from .barcode import generate_barcode
from .forms import (AssetForm,AssignedAssetListForm,AssetImageForm,ReassignedAssetForm)
from .models import Asset, AssetImage, AssetSpecification, AssetStatus, AssignAsset
from .utils import (asset_details, autogenerated_tag, create_char_data, create_custom_fileds,delete_asset_images, filtered_asset,create_asset_list, save_new_images, search_with_filters, update_existing_custom_fields)

IS_DEMO = os.environ.get('IS_DEMO')
PAGE_SIZE = 10
ORPHANS = 1

def check_admin(user):
    return user.is_superuser

def manage_access_for_assets(user):
    permissions_list = [
        'authentication.edit_asset',
        'authentication.view_asset',
        'authentication.delete_asset',
        'authentication.add_asset',
    ]

    for permission in permissions_list:
        if user.has_perm(permission):
            return True

    return False

def manage_access_for_assign_assets(user):
    permissions_list = [
        'authentication.reassign_assign_asset',
        'authentication.add_assign_asset',
        'authentication.delete_assign_asset',
    ]

    for permission in permissions_list:
        if user.has_perm(permission):
            return True

    return False

@login_required
@user_passes_test(manage_access_for_assets)
def listed(request):
    assets_qs=filtered_asset(request)
    context=create_asset_list(request,assets_qs)
    return render(request, 'assets/list.html', context=context)

@login_required
@permission_required('authentication.view_asset')
def details(request, id):
    get_audit_history=Audit.objects.filter(asset_id=id)
    get_audit_image=AuditImage.objects.filter(audit__asset__id=id).order_by('-uploaded_at').first()
    asset = Asset.objects.filter(pk=id, organization=request.user.organization).first()
    assiggned_asset=AssignAsset.objects.filter(asset=asset).first()  
    assetSpecifications = AssetSpecification.objects.filter(asset=asset)
    get_asset_img=AssetImage.objects.filter(asset=asset).order_by('-uploaded_at').values()
    asset_barcode = generate_barcode(asset.tag)
    context=asset_details(request,get_audit_history,get_audit_image,asset,assiggned_asset,assetSpecifications,get_asset_img,asset_barcode)
    
    return render(request, 'assets/detail.html', context=context)

@login_required
@permission_required('authentication.add_asset')
def add(request):
    if request.method == 'POST':
        form = AssetForm(request.POST, organization=request.user.organization_id)
        if form.is_valid():
            asset = form.save(commit=False)
            asset.organization = request.user.organization
            available_status = AssetStatus.objects.filter(name='Available').first()
            asset.asset_status = available_status 
            asset.save()
            form.save_m2m()
            # Save images
            for image_file in request.FILES.getlist('image'):
                AssetImage.objects.create(asset=asset, image=image_file)
                
            create_custom_fileds(request,asset)
            return redirect('assets:list')
    else:
        form = AssetForm(organization=request.user.organization_id)
        autogenerated_tag(request,form)
        image_form = AssetImageForm()

    context = {
        'form': form,
        'image_form': image_form,
        'title': 'Add Asset',
    }
    return render(request, 'assets/add.html', context)


@login_required
@permission_required('authentication.delete_asset')
def delete(request, id):
    if request.method == "POST":
        asset = get_object_or_404(
            Asset.undeleted_objects, pk=id)
        if asset.is_assigned:
            messages.error(
                request, 'Error! Asset is assigned to a user')
        else:
            asset.soft_delete()
            history_id = asset.history.first().history_id
            asset.history.filter(pk=history_id).update(history_type='-')
            messages.success(request, 'Asset deleted successfully.')

    return redirect('assets:list')

@login_required
def search(request):
        list_of_audits=Audit.objects.all()
        list_of_assigned_audits=[audit.asset.id for audit in list_of_audits ]
        list_of_audited_assets=Asset.objects.filter(id__in=list_of_assigned_audits)
        
        context=search_with_filters(request,list_of_audited_assets)

        return render(request, 'assets/assets-data.html', context=context)

@login_required
@user_passes_test(manage_access_for_assign_assets)
def assigned_list(request):

    assign_asset_list = AssignAsset.objects.filter(
        asset__organization=request.user.organization or None).order_by('-asset__created_at')
    paginator = Paginator(assign_asset_list, PAGE_SIZE, orphans=ORPHANS)
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)

    context = {
        'sidebar': 'assets',
        'submenu': 'assigned-assets',
        'page_object': page_object,
        'title': 'Assigned Assets'
    }

    return render(request, 'assets/assigned-list.html', context=context)


@login_required
@permission_required('authentication.delete_assign_asset')
def delete_assign(request, id):
    if request.method == 'POST':
        assignAsset = get_object_or_404(
            AssignAsset, pk=id, asset__organization=request.user.organization)
        assignAsset.delete()
        assignAsset.asset.is_assigned = False
        set_asset=AssetStatus.objects.filter(Q(organization=request.user.organization) | Q(organization__isnull=True), name='Available').first()
        assignAsset.asset.asset_status=set_asset
        assignAsset.asset.save()
        messages.success(request, 'Asset unassigned successfully')
    return redirect('assets:assigned_list')

@login_required
def change_status(request, id):
    if request.method in ['PATCH', 'POST']:
        try:
            asset = Asset.objects.filter(id=id).first()
        except Asset.DoesNotExist:
            return JsonResponse({'error': 'Asset not found'}, status=404)
        try:
            data = json.loads(request.body)
            new_status = (data.get('status'))
        except (ValueError, KeyError, json.JSONDecodeError)as e:
            return HttpResponseBadRequest('Invalid data')
        get_status=AssetStatus.objects.filter(Q(organization=request.user.organization) | Q(organization__isnull=True), name=new_status).first()
        asset.asset_status = get_status
        asset.updated_by=request.user.full_name
        if asset.asset_status != "Available":  # If status is 'Assigned'
            asset.is_assigned = False
            # delete the assigned asset from the asigned asset list
            AssignAsset.objects.filter(asset=asset).delete()
        asset.save()
        return JsonResponse({'success': True, 'new_status': new_status})


    return JsonResponse({'error': 'Invalid method'}, status=405)

def delete_assign_asset_list(request, id):
    if request.method == 'POST':
        asset=Asset.objects.filter(id=id).first()
        asset.is_assigned=False
        set_asset=AssetStatus.objects.filter(Q(organization=request.user.organization) | Q(organization__isnull=True), name='Available').first()
        asset.asset_status=set_asset
        asset.save()
        assignAsset = get_object_or_404(
            AssignAsset, asset=asset, asset__organization=request.user.organization)
        assignAsset.delete()
    return redirect('assets:list')

@login_required
@permission_required('authentication.edit_asset')
def update_in_detail(request, id):
    asset = get_object_or_404(Asset, pk=id, organization=request.user.organization)
    org = request.user.organization

    asset_images = AssetImage.objects.filter(asset=asset)
    asset_specs = AssetSpecification.objects.filter(asset=asset)
    custom_fields = CustomField.objects.filter(
        entity_type='asset', object_id=asset.id, organization=org
    )
    if request.method == 'DELETE':
        print('method called')
        return delete_asset_images(request, asset)

    if request.method == 'POST':
        form = AssetForm(request.POST, instance=asset, organization=org)
        image_form = AssetImageForm(request.POST, request.FILES)

        if form.is_valid() and image_form.is_valid():
            form.save()

            save_new_images(request, asset)
            update_existing_custom_fields(request, custom_fields)

            messages.success(request, "Asset updated successfully.")
            return redirect(f'/assets/details/{asset.id}')

    else:
        form = AssetForm(instance=asset, organization=org)
        image_form = AssetImageForm()

    context = {
        'sidebar': 'assets',
        'submenu': 'list',
        'form': form,
        'image_form': image_form,
        'asset_images': asset_images,
        'asset': asset,
        'assetSpecifications': asset_specs,
        'custom_fields': custom_fields,
        'title': f'Update-{asset.tag}-{asset.name}',
    }
    if request.path == f'/assets/update-assets-details/{id}/':
        return render(request, 'assets/update-assets-in-detail.html', context)
    else:
        return render(request, 'assets/update-assets.html', context)


def piechart_status_data(request):
    data = Asset.objects.values('asset_status__name').annotate(total=Count('id'))
    return data

def pie_chart_assigned_status(request):
    data = Asset.objects.all()
    chart_data=create_char_data(data)
    return JsonResponse({'chart_data': chart_data})

def pie_chart_status(request):
    data = Asset.undeleted_objects.values('asset_status__name').annotate(total=Count('id'))
    no_data=None
    if data is None:
        no_data='No Data Found'
    chart_data = [['Status', 'Assets']]
    for item in data:
        chart_data.append([item['asset_status__name'], item['total']])
    filtered_chart_data = [row for row in chart_data if row[0] is not None]
    return JsonResponse({'chart_data': filtered_chart_data,'no_data':no_data})


@login_required
@permission_required('assets.change_asset', raise_exception=True)
def assign_assets(request, id):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        asset = get_object_or_404(Asset, pk=id, organization=request.user.organization)
        selected_user = get_object_or_404(User, pk=user_id, is_active=True)
        
        # Create or update the AssignAsset record
        assign_obj, created = AssignAsset.objects.update_or_create(
            asset=asset,
            defaults={'user': selected_user},
        )
        # Mark asset as assigned
        asset.is_assigned = True
        set_asset=AssetStatus.objects.filter(Q(organization=request.user.organization) | Q(organization__isnull=True), name='Assigned').first()
        asset.asset_status=set_asset
        # asset.status = 0  # 0 = 'Assigned' by your STATUS_CHOICES
        asset.save()

        messages.success(request, f"Asset assigned to user.")
        return redirect('assets:list')

def assign_asset_in_asset_list(request, id):
    asset = get_object_or_404(Asset, pk=id, organization=request.user.organization)
    form = AssignedAssetListForm(request.POST,organization=request.user.organization)
    image_form = AssetImageForm(request.FILES)
    if request.method == 'POST':
        if form.is_valid() and image_form.is_valid():
            assign_obj = form.save(commit=False)
            assign_obj.asset = asset
            assign_obj.save()
            form.save_m2m()
            asset.is_assigned = True
            asset.asset_status = AssetStatus.objects.filter(Q(organization=request.user.organization) | Q(organization__isnull=True), name='Assigned').first()
            asset.save()
            files = request.FILES.getlist('images')

            for f in files:
                AssetImage.objects.create(asset=asset, image=f)
            messages.success(request, 'Asset assigned to user successfully')
            return HttpResponse(status=204)
        else:
            return redirect('assets:list')
    else:
        form = AssignedAssetListForm(organization=request.user.organization)
        image_form = AssetImageForm()
    context = {'form': form,'image_form':image_form,'asset':asset}
    return render(request, 'assets/assign-asset-modal-in-list.html', context=context)

def assign_asset_search(request, page):
    search_text = request.GET.get('search_text').strip()
    if search_text:
        return render(request, 'assets/assigned-assets-data.html', {
            'page_object': AssignAsset.objects.filter(Q(asset__organization=request.user.organization) & (Q(
                asset__name__icontains=search_text) | Q(asset__serial_no__icontains=search_text) | Q(user__full_name__icontains=search_text) | Q(user__department__name__icontains=search_text)
            )).order_by('-asset__created_at')[:10]
        })

    asset_list = AssignAsset.objects.filter(
        asset__organization=request.user.organization).order_by('-asset__created_at')
    paginator = Paginator(asset_list, PAGE_SIZE, orphans=ORPHANS)
    page_number = page
    page_object = paginator.get_page(page_number)
    return render(request, 'assets/assigned-assets-data.html', {'page_object': page_object})

@login_required
@permission_required('authentication.reassign_assign_asset')
def reassign_asset(request, id):
    assignAsset = get_object_or_404(
        AssignAsset, pk=id, asset__organization=request.user.organization)
    form = ReassignedAssetForm(
        request.POST or None, instance=assignAsset, organization=request.user.organization)
    if request.method == 'POST':
        if form.is_valid():
            form.save()

            messages.success(
                request, 'Asset re-assigned successfully')
            return HttpResponse(status=204)
    context = {'form': form}
    return render(request, 'assets/reassign-asset-modal.html', context=context)