# Generated by Django 5.2.8 on 2025-11-21 07:05

import audit.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0027_alter_asset_tag_alter_historicalasset_tag'),
        ('dashboard', '0025_alter_address_created_at_alter_address_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.CharField(blank=True, max_length=150, null=True)),
                ('condition', models.IntegerField(choices=[(0, 'Excellent'), (1, 'Good'), (2, 'Fair'), (3, 'Bad'), (4, 'Retired')], default=0)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='assets.asset')),
                ('audited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuditImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=audit.models.path_and_rename)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='audit.audit')),
            ],
        ),
    ]
