# Generated by Django 5.2.8 on 2025-11-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='image',
        ),
        migrations.AlterField(
            model_name='audit',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
