# Generated by Django 3.2 on 2022-12-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20221213_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='organization',
        ),
    ]
