# Generated by Django 3.2 on 2023-01-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_remove_file_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
