# Generated by Django 5.1.5 on 2025-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_alter_file_file_importeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeduser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
