# Generated by Django 5.1.5 on 2025-07-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_importeduser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importeduser',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
