# Generated by Django 5.1.5 on 2025-09-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_alter_importeduser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importeduser',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
