# Generated by Django 5.2.14 on 2026-07-21 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_historicallocation_client_location_client"),
        ("upload", "0013_remove_importeduser_roles_importeduser_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkUploadSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "csv_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "zip_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("staged_data", models.JSONField(default=list)),
                ("image_map", models.JSONField(default=dict)),
                ("total_rows", models.IntegerField(default=0)),
                ("matched_images", models.IntegerField(default=0)),
                ("unmatched_images", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("mapped", "Mapped"),
                            ("committed", "Committed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Upload Session",
                "ordering": ["-created_at"],
            },
        ),
    ]
