# Generated by Django 5.2.14 on 2026-07-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0014_bulkuploadsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkuploadsession",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bulkuploadsession",
            name="created_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bulkuploadsession",
            name="import_errors",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="bulkuploadsession",
            name="processed_rows",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bulkuploadsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("mapped", "Mapped"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("committed", "Committed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
