# Generated by Django 5.2.13 on 2026-08-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_fields", "0002_alter_customfielddefinition_customfieldvalue_db_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfielddefinition",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("integer", "Integer"),
                    ("decimal", "Decimal"),
                    ("date", "Date"),
                    ("boolean", "Boolean (Yes/No)"),
                    ("email", "Email"),
                ],
                default="text",
                max_length=30,
            ),
        ),
    ]
