# Generated by Django 5.2.13 on 2026-08-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_fields", "0003_alter_customfielddefinition_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfielddefinition",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
