# Generated by Django 5.2.16 on 2026-08-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0004_customfielddefinition_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='module',
            field=models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor'), ('product', 'Product'), ('user', 'User'), ('asset', 'Asset'), ('support_ticket', 'Support Ticket'), ('maintenance', 'Maintenance')], max_length=30),
        ),
    ]
