# Generated by Django 3.2 on 2022-11-11 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_delete_employee'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.organization'),
        ),
        migrations.AddField(
            model_name='role',
            name='related_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
