# Generated by Django 3.2 on 2023-01-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20221111_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
