# Generated by Django 3.2 on 2022-09-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20220703_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
