# Generated by Django 3.2 on 2022-09-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_rename_deleted_vendor_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
