# Generated by Django 3.2 on 2022-09-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='deleted',
        ),
    ]
