# Generated by Django 3.2 on 2023-01-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_historicalvendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvendor',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
