# Generated by Django 5.1.5 on 2025-10-23 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_tagconfiguration'),
        ('dashboard', '0025_alter_address_created_at_alter_address_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizationConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_format', models.IntegerField(blank=True, max_length=50, null=True)),
                ('time_format', models.IntegerField(blank=True, max_length=50, null=True)),
                ('timezone', models.IntegerField(blank=True, max_length=100, null=True)),
                ('currency', models.IntegerField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.organization')),
            ],
        ),
    ]
