# Generated by Django 5.1.5 on 2025-10-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_localizationconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizationconfiguration',
            name='country_format',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localizationconfiguration',
            name='default_language',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localizationconfiguration',
            name='name_display_format',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localizationconfiguration',
            name='currency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localizationconfiguration',
            name='date_format',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localizationconfiguration',
            name='time_format',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localizationconfiguration',
            name='timezone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
