# Generated by Django 5.1.5 on 2025-11-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensions',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0),
        ),
    ]
