# Generated by Django 5.1.5 on 2025-11-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_alter_extensions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensions',
            name='validity',
            field=models.IntegerField(default=0),
        ),
    ]
