# Generated by Django 5.1.5 on 2025-11-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0008_slackconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
