# Generated by Django 5.2.16 on 2026-09-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0009_extensions_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
