# Generated by Django 5.2.16 on 2026-08-22 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0009_extensions_description"),
        ("dashboard", "0029_customfielddefinition_customfieldvalue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstalledExtension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("app_label", models.CharField(max_length=100, unique=True)),
                ("version", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("installed", "Installed"),
                            ("pending_restart", "Pending Restart"),
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("error", "Error"),
                        ],
                        default="installed",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("local", "Local"), ("github", "GitHub")],
                        max_length=10,
                    ),
                ),
                ("source_url", models.CharField(blank=True, max_length=500, null=True)),
                ("manifest_json", models.JSONField()),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExtensionLicense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("activation_token", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("invalid", "Invalid"),
                        ],
                        default="invalid",
                        max_length=20,
                    ),
                ),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.organization",
                    ),
                ),
                (
                    "extension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="configurations.installedextension",
                    ),
                ),
            ],
        ),
    ]
