# Generated by Django 5.2.14 on 2026-09-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0010_configurationpermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtensionsPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
