# Generated by Django 5.2.13 on 2026-05-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "support",
            "0002_historicalsupportticket_supportticket_ticketactivity_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Support",
        ),
    ]
