# Generated by Django 5.2.13 on 2026-06-30 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_historicalsupportticket_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.ticketactivity'),
        ),
    ]
