# Generated by Django 5.2.14 on 2026-07-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0009_ticketcomment_is_staff_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsupportticket",
            name="happy_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="happy_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
