# Generated by Django 5.2.14 on 2026-07-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0010_historicalsupportticket_happy_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsupportticket",
            name="created_by_contact",
        ),
        migrations.RemoveField(
            model_name="historicalsupportticket",
            name="service_level",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="created_by_contact",
        ),
        migrations.RemoveField(
            model_name="supportticket",
            name="service_level",
        ),
    ]
