# Generated by Django 3.2 on 2022-11-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_usernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_view',
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
