# Generated by Django 3.2 on 2022-11-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20221102_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='role',
        ),
    ]
