# Generated by Django 5.2.7 on 2025-10-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
