# Generated by Django 5.2.8 on 2025-12-04 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license", "0003_historicallicense"),
        ("vendors", "0009_alter_historicalvendor_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendors.vendor",
            ),
        ),
    ]
