# Generated by Django 5.2.8 on 2025-12-31 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license", "0004_alter_license_vendor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallicense",
            name="is_assigned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="license",
            name="is_assigned",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AssignLicense",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("notes", models.TextField(blank=True)),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                (
                    "license",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="license.license",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
