# Generated by Django 5.2.8 on 2025-12-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license", "0005_assignlicense"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallicense",
            name="is_assigned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="license",
            name="is_assigned",
            field=models.BooleanField(default=False),
        ),
    ]
