# Generated by Django 3.2 on 2022-09-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_product_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_pic',
            new_name='product_picture',
        ),
    ]
