# Generated by Django 3.2 on 2022-09-27 06:55

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_product_pic_product_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.path_and_rename),
        ),
    ]
