# Generated by Django 3.2 on 2022-09-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_product_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
