# Generated by Django 5.2.8 on 2025-11-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_historicalproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='audit_interval',
            field=models.IntegerField(choices=[(1, 'Yearly'), (2, 'Bi Monthly'), (3, 'Quarterly'), (4, 'Half Yearly'), (5, 'Monthly'), (6, 'Not Applicable')], default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='audit_interval',
            field=models.IntegerField(choices=[(1, 'Yearly'), (2, 'Bi Monthly'), (3, 'Quarterly'), (4, 'Half Yearly'), (5, 'Monthly'), (6, 'Not Applicable')], default=1),
        ),
    ]
