# Generated by Django 5.2.8 on 2025-11-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_historicalproduct_audit_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='audit_interval',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Yearly'), (2, 'Half Yearly'), (3, 'Quarterly'), (4, 'Bi Monthly'), (5, 'Monthly')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='audit_interval',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Yearly'), (2, 'Half Yearly'), (3, 'Quarterly'), (4, 'Bi Monthly'), (5, 'Monthly')], default=1),
        ),
    ]
