# Generated by Django 5.2.8 on 2025-11-26 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_address_created_at_alter_address_status_and_more'),
        ('products', '0018_historicalproduct_audit_interval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='product_category',
            new_name='product_sub_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='product_sub_category',
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='audit_interval',
            field=models.IntegerField(choices=[(0, 0), (1, 365), (2, 182), (3, 90), (4, 60), (5, 30)], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='audit_interval',
            field=models.IntegerField(choices=[(0, 0), (1, 365), (2, 182), (3, 90), (4, 60), (5, 30)], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.producttype'),
        ),
    ]
